<a href="https://colab.research.google.com/github/Daria1325/Neural_Network_2022/blob/main/lab1/Lab1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Лабораторна робота №1 <br>
З дисципліни "Нейронні мережі"<br>
студентки КН-31<br>
Боженко Дар'ї<br>


##Завдання
1. Ознайомлення з можливостями, налаштувати середовища Google colab.
2. NumPy (створити набір даних (розмір за власним рішенням), провести CRUD операції над даними (скаляр, вектор, матриця)). Властивість shape та метод reshape. Операції над масивами. Використати arange, random.

In [37]:
import numpy as np

#створити набір даних
A = np.array([1,5,4,7,8,9,6,4,5])
print(A)

#провести CRUD операції ????
#скаляр
a = np.random.randint(10,20)
print("scalar\n", a)
a = 5
print(a)
#????delete



#вектор
b = np.arange(3, 10, 1)
print("vector\n", b)
b=np.random.shuffle(b)
print(b)
b = np.append(b,[1,2,3],0)
print(b)
#матриця
c = np.array([[4,7,8],[5,7,6],[10,7,8]])
print("matrix\n",c)
c[0][0] = 5
print(c)


print(A.shape)
A = A.reshape((3,3))
print(A)


[1 5 4 7 8 9 6 4 5]
scalar
 12
5
vector
 [3 4 5 6 7 8 9]
[5 3 7 6 9 8 4]
[5 3 7 6 9 8 4 1 2 3]
matrix
 [[ 4  7  8]
 [ 5  7  6]
 [10  7  8]]
[[ 5  7  8]
 [ 5  7  6]
 [10  7  8]]
(9,)
[[1 5 4]
 [7 8 9]
 [6 4 5]]


In [36]:
#операції над масивами
print("A\n", A)
print("c\n",c)
print("A+c\n",A+c)

print("A*c\n",A*c)
print("dot(A,c)\n",np.dot(A,c))
print("A*5\n",A*5)
print("A-c\n",A-c)
print("A/c\n",A/c)

A
 [[1 5 4]
 [7 8 9]
 [6 4 5]]
c
 [[ 5  7  8]
 [ 5  7  6]
 [10  7  8]]
A+c
 [[ 6 12 12]
 [12 15 15]
 [16 11 13]]
A*c
 [[ 5 35 32]
 [35 56 54]
 [60 28 40]]
dot(A,c)
 [[ 70  70  70]
 [165 168 176]
 [100 105 112]]
A*5
 [[ 5 25 20]
 [35 40 45]
 [30 20 25]]
A-c
 [[-4 -2 -4]
 [ 2  1  3]
 [-4 -3 -3]]
A/c
 [[0.2        0.71428571 0.5       ]
 [1.4        1.14285714 1.5       ]
 [0.6        0.57142857 0.625     ]]


3. Pandas (створити dataframe різними способами, провести маніпуляції з даними (head, describe, iloc, loc, індексація з умовами відбору,групування, пошук «пустих» значень, сортування.);

In [ ]:
import os
import pandas as pd

4. Matplotlib (створити набір даних лінійної функції з урахуванням помилок вимірювань, побудувати графік функції та згенерованих даних, обчислити похибку з використанням метрик MAE, MSE). Записати отримані результати у csv файл (формат: X,Y, Y_hat, mAE, mSE)