<a href="https://colab.research.google.com/github/Daria1325/Neural_Network_2022/blob/main/Lab2/Lab2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Лабораторна робота №2 <br>
З дисципліни "Нейронні мережі"<br>
студентки КН-31<br>
Боженко Дар'ї<br>

##Завдання
1. За матеріалами ознайомитись із засадами бібліотеки TensorFlow:
- засвоєння поняття тензору
- знати різні способи створення тензорів
- створити набір даних із заданим розподілом (розподіл та розмір за власним
рішенням), визначити його властивості (shape, rank, size, axis)
- продемонструвати основні математичні операції над тензорами
- провести CRUD операції над даними, reshape, інтеграцію з np.array, pd.DataFrame)
2. Відповіді оформити .ipynb документами за кожним з попередніх пунктів
3. Викласти у зазначений репозіторій GitHub в окремій папці з назвою Lab2 де мають бути .ipynb файл та необхідні файли з даними

## Знати різні способи створення тензорів

In [1]:
import  tensorflow  as  tf 
import numpy as np

#vector
vector = tf.constant([10, 10])
print(vector)

#matrix
matrix = tf.constant([[10, 7], [7, 10]])
print(matrix)

#changeble
changeable_tensor = tf.Variable([10, 7])
print(changeable_tensor)

# Make a tensor of all ones
tf.ones(shape=(3, 2))

tf.Tensor([10 10], shape=(2,), dtype=int32)
tf.Tensor(
[[10  7]
 [ 7 10]], shape=(2, 2), dtype=int32)
<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([10,  7], dtype=int32)>


<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
array([[1., 1.],
       [1., 1.],
       [1., 1.]], dtype=float32)>

## Cтворити набір даних із заданим розподілом (розподіл та розмір за власним рішенням), визначити його властивості (shape, rank, size, axis)

In [3]:
#нормальний розподіл
tensor = tf.random.Generator.from_seed(5) 
tensor = tensor.normal(shape=(4, 2))
print(tensor)

print("Shape of tensor:", tensor.shape)
print("Rank of tensor:", tensor.ndim)
print("Elements along axis 0 of tensor:", tensor.shape[0])
print("Elements along last axis of tensor:", tensor.shape[-1])
print("Total number of elements:", tf.size(tensor).numpy())

tf.Tensor(
[[ 1.0278524   0.27974114]
 [-0.01347923  1.845181  ]
 [ 0.97061104 -1.0242516 ]
 [-0.6544423  -0.29738766]], shape=(4, 2), dtype=float32)
Shape of tensor: (4, 2)
Rank of tensor: 2
Elements along axis 0 of tensor: 4
Elements along last axis of tensor: 2
Total number of elements: 8


## Продемонструвати основні математичні операції над тензорами

In [14]:
tensor2 = tf.constant(np.arange(1, 9))
tensor2 = tf.cast(tensor2, dtype=tf.float32)
tensor2=tf.reshape(tensor2,(2,4))
print("\ntensor2\n",tensor2)

print("\n tensor + 10\n",tensor+10)
print("\n tensor * 5\n",tensor*5)
print("\n matrix multiplication\n",tf.matmul(tensor, tensor2))
print("\n tensor square\n",tf.square(tensor2*10))


tensor2
 tf.Tensor(
[[1. 2. 3. 4.]
 [5. 6. 7. 8.]], shape=(2, 4), dtype=float32)

 tensor + 10
 tf.Tensor(
[[11.027852  10.279741 ]
 [ 9.986521  11.8451805]
 [10.970611   8.975748 ]
 [ 9.345558   9.702612 ]], shape=(4, 2), dtype=float32)

 tensor * 5
 tf.Tensor(
[[ 5.139262    1.3987057 ]
 [-0.06739616  9.225904  ]
 [ 4.853055   -5.121258  ]
 [-3.2722116  -1.4869382 ]], shape=(4, 2), dtype=float32)

 matrix multiplication
 tf.Tensor(
[[ 2.426558   3.7341516  5.041745   6.3493385]
 [ 9.212425  11.044127  12.87583   14.707531 ]
 [-4.1506467 -4.2042875 -4.257928  -4.3115683]
 [-2.1413805 -3.0932107 -4.0450406 -4.9968705]], shape=(4, 4), dtype=float32)

 tensor square
 tf.Tensor(
[[ 100.  400.  900. 1600.]
 [2500. 3600. 4900. 6400.]], shape=(2, 4), dtype=float32)


## Провести CRUD операції над даними, reshape, інтеграцію з np.array

In [15]:
# reshape
print(tf.reshape(tensor2,(1,8)))

#інтеграція з np.array
print(tensor2.numpy())

del(tensor2)




tf.Tensor([[1. 2. 3. 4. 5. 6. 7. 8.]], shape=(1, 8), dtype=float32)
[[1. 2. 3. 4.]
 [5. 6. 7. 8.]]


## Висновок
У ході лабораторної роботи було набуто практичних навичок з роботи з такими сервісами як GoogleColab та GitHub. Я ознайомилася з функціоналом бібліотеки TensorFlow та її можливостями.